module tb_and_gate;
reg A;
reg B;
wire Y;

and_gate uut(
    .A(A),
    .B(B),
    .Y(Y)
);
 initial begin
    
     $dumpfile("dump.vcd");
     $dumpvars(0, tb_and_gate);
     A=0; B=0;
     #10;
     A=0;B=1;
     #10;
     A=1;B=0;
     #10;
     A=1;B=1;
     #10;
 end
 endmodule